### ISSUE TITLE
Error: No template folder

### ISSUE THREAD

**Issue by poupryc** [tamiadev/tamia-changelog#1]
Hello, when I run tamia-changelog, I have this:

```
$ npx tamia-changelog
ENOENT: no such file or directory, open 'project/node_modules/tamia-changelog/templates/template.hbs'
```

**Comment by sapegin** [comment]
Sorry, forget to publish them to npm, should be fixed: https://github.com/tamiadev/tamia-changelog/releases/tag/v1.0.1

**Comment by poupryc** [comment]
I can't comment, I finally switched my project to semantic-release only ! Good luck
